#!/usr/bin/env bash
# The count of windows SUPER+I has put away, as waybar JSON.
#
# Replaced `wlr/taskbar`, which listed every open window — the list the
# workspace tags already give you — where the only windows you cannot see from
# the bar are the minimized ones. docs/adr/0051.
#
# A COUNT AND ONE ICON, not a glyph per window. The icon is the stylesheet's
# (`-gtk-icontheme()`, generated by modules/home/waybar.nix) and GTK gives a
# module one background image, not one per item. The per-window art is
# menus/minimized-menu.sh's, where a rofi row carries its own icon.
#
# The click opens that picker, which restores a SPECIFIC window with
# `mmsg dispatch focusid client,<id>`. docs/adr/0033 refused a picker here while
# `restore_minimized` was the only verb — it takes no client and pops the last
# one on the current tag, so the menu could not honour the choice it accepted.
# `focusid client,<id>` can, verified 2026-08-28. docs/adr/0052.

# waybar kills this module by closing its pipe, and the `mmsg watch` inside the
# process substitution below does not go with it — four orphans were alive at
# once on 2026-08-16 from the sibling script, each holding 5 MB and an open IPC
# socket. `-P $$` targets this script's own children by parent rather than by
# name, which is both exact and safe. The signal traps `exit` and leave the
# reaping to the EXIT trap: a handler that does not exit REPLACES the default
# action, which is how the first version of the sibling's fix made the script
# immune to sigterm and leaked itself instead. docs/gotchas.md -> Scripts.
cleanup() { pkill -P $$ 2>/dev/null; }
trap cleanup EXIT
trap 'exit 0' PIPE HUP INT TERM

# `class` is what CSS collapses on. An empty text still draws `.module`'s
# padding, which is 10px of dead bar in the resting state — the same 10px that
# was reported as bluetooth's padding on the wayle bar (docs/gotchas.md).
emit() {
	local out
	out=$(jq -c '
		[.clients[]? | select(.is_minimized == true)] as $m
		| { text:    (if ($m | length) == 0 then "" else ($m | length | tostring) end),
		    tooltip: ($m | map(.title // .appid // "?") | join("\n")),
		    class:   (if ($m | length) == 0 then "empty" else "some" end) }
	' 2>/dev/null) || out=""
	# A jq that failed prints nothing, and waybar holds a module's last value
	# when its update yields nothing — so the bar would keep showing a count
	# that has stopped tracking anything. Say so instead.
	[ -n "$out" ] || out='{"text":"?","tooltip":"minimized.sh: the client list did not parse","class":"error"}'
	printf '%s\n' "$out"
}

# Seed from a one-shot so the module is populated before the first change.
mmsg get all-clients 2>/dev/null | emit

while true; do
	while IFS= read -r line; do
		[ -n "$line" ] || continue
		printf '%s' "$line" | emit
	done < <(mmsg watch all-clients 2>/dev/null)

	# Stream ended (compositor reload/restart) — back off and reconnect. No
	# empty emit first, unlike window-title.sh: a title that is stale is wrong,
	# but the minimized set does not change because the bar lost its stream.
	sleep 1
done
