cursor #ebdbb2
cursor_text_color #d5c4a1

foreground            #ebdbb2
background            #282828
selection_foreground  #282828
selection_background  #fe8019
url_color             #d3869b

color0   #282828
color1   #f26d71
color2   #83d369
color3   #ffe272
color4   #c97189
color5   #612032
color6   #d3869b
color7   #ddd0d3
color8   #8b8083
color9   #ff9fa2
color10  #bafda4
color11  #ffeca5
color12  #e8a0b3
color13  #ffbdcf
color14  #ffd5e0
color15  #fff8fa
