exec=pkill waybar 2>/dev/null; true
exec=pkill -x dsearch 2>/dev/null; true
exec=pkill -x swaync 2>/dev/null; swaync -s ~/.config/mango/swaync/style.css &
exec=~/.config/mango/scripts/waybar/waybar-restart.sh
exec=~/.config/mango/scripts/system/gtk-apply.sh
exec=ln -sf ~/.config/mango/walker/configs/hud.toml ~/.config/mango/walker/config.toml
exec=pgrep -x kdeconnectd || kdeconnectd
exec=pgrep -x elephant || elephant
exec=~/.config/mango/scripts/walker/walker-daemon.sh
