[theme]
background         = "#282828"
primary            = "#c9b890"
secondary          = "#7a6a50"
title              = "#d4a039"
playing            = "#89aa61"
playing_selected   = "#89aa61"
playing_bg         = "#2e2720"
highlight          = "#3d352c"
highlight_fg       = "#c9b890"
error_bg           = "#ad401f"
error_fg           = "#c9b890"
statusbar_progress = "#d4a039"
statusbar_progress_bg = "#3d352c"
statusbar          = "#c9b890"
statusbar_bg       = "#2e2720"
cmdline            = "#c9b890"
cmdline_bg         = "#2e2720"
search_match       = "#d4a039"
border             = "#3d352c"
