# ~/.config/zsh/conf.d/10-aliases.zsh

scripts="$HOME/.scripts"

# --- ls / eza ------------------------------------------------------
# NixOS's /etc/zshrc (programs.zsh.enable) predefines ls/l/ll from
# environment.shellAliases. `ls` being an alias makes the ls() function below
# a parse error, which aborts the rest of this file — so clear them first.
unalias ls l ll 2>/dev/null

alias l='ls'
# `ls`/`l` hide personal top-level dirs *only while in $HOME* (mirrors ~/.hidden).
# Elsewhere, or with any argument (e.g. `ls foo`), nothing is filtered.
# `ll`, `la`, `lla`, `lls` are unfiltered — use them to see everything.
_HOME_HIDE='Android|Applications|blender|colors|go|log|R|share|temp|vaults|winboat|Zomboid'
ls() {
  if [[ $PWD == $HOME && $# -eq 0 ]]; then
    command eza --color=always --icons=always --ignore-glob="$_HOME_HIDE"
  else
    command eza --color=always --icons=always "$@"
  fi
}
alias la='eza -a --color=auto --icons=auto'
alias ll='eza -la --no-time'
alias lla='eza -lah --total-size'
alias lls='eza -lah --total-size'

# --- general -------------------------------------------------------
alias zed='zeditor'
alias cat='bat'
alias lf='yazi'
alias open='xdg-open'
# The binary is `zen-beta` on NixOS (beta channel via the zen-browser flake);
# `zen-browser` was the Arch name and does not exist here.
alias zen='zen-beta'
alias mntandroid='simple_mtpfs'

# dot-dot navigation
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'

# git
alias gs='git status -sb'
alias gl='git log --oneline --graph --decorate'

# --- Privilege & System Commands -----------------------------------
#if (( EUID != 0 )); then
#  alias sudo='sudo-rs'
#  alias lidt="sudo \"$scripts\"/toggle_lid_action.sh /etc/systemd/logind.conf"
#  alias cleantmp="sudo \"$scripts\"/clean_tmp.sh"
#  
#  function pacman() {
#    case $1 in
#      -S|-D|-R|-U|--sync|--database|--remove|--upgrade) command sudo pacman "$@" ;;
#      *) command pacman "$@" ;;
#    esac
#  }
#else
  # Safely neuter sudo if operating cleanly as root
#  alias sudo='command '
#fi

# --- yazi integration (y) ------------------------------------------
# The `y` wrapper (cd to yazi's exit directory) is GENERATED by
# `programs.yazi.enableZshIntegration` in modules/home/programs.nix, with
# `shellWrapperName = "y"`. It used to be hand-written here, which meant two
# near-identical definitions of the same function: home-manager emitted `yy()`
# into ~/.zshrc while this file defined `y()`.
#
# That was survivable only by accident of ordering — programs.zsh sources
# conf.d/*.zsh AFTER its own init, so whichever name collided, this file won.
# home-manager is changing the wrapper's default name from `yy` to `y`, at
# which point the two would have collided outright and the winner would have
# been decided by source order rather than by anyone's intent. Deleted here and
# declared there instead. Don't reintroduce it.

# --- zoxide (cd) ---------------------------------------------------
# Declared by `programs.zoxide` in modules/home/shell.nix. Duplicated here
# until 2026-08-01, costing ~8 ms per shell.
