bind=SUPER,space,spawn,foot -a fsel-launcher -e fsel --detach
bind=SUPER,w,spawn,~/.config/mango/scripts/walker/walker.sh -m providerlist
bind=SUPER+CTRL,O,spawn,~/.config/mango/scripts/walker/walker.sh -m obsidian
bind=SUPER,p,spawn,~/.config/mango/scripts/walker/walker.sh -m bitwarden --maxheight 300 --width 400
bind=SUPER,v,spawn,~/.config/mango/scripts/walker/walker.sh -m clipboard
bind=SUPER+CTRL,n,spawn,~/.config/mango/scripts/menus/network-menu.sh
bind=SUPER+CTRL,v,spawn,~/.config/mango/scripts/menus/vpn-menu.sh
bind=SUPER+CTRL,b,spawn,~/.config/mango/scripts/walker/walker.sh -m bluetooth

bind=SUPER+SHIFT,s,spawn,lockscreen -f
