#!/usr/bin/env bash
# Usage: weather.sh <status|read|refresh>
#
# The one owner of "what the weather is" here; custom/weather and the
# control-centre row are both readers. docs/adr/0038.
#
#   status   the bar        fetches when the cache has expired
#   read     the menu row   cache only, NEVER a socket — that render is parallel
#                           and costs its slowest row (73 ms). Asserted.
#   refresh  Enter on it    fetches past the TTL, then signals waybar
#
# Three classes, because a served cache that does not say it is one is
# yesterday's temperature in today's font: `ok`, `stale` (greyed, with its age)
# and `error` (`?`, never a number).

set -u

. "$HOME/.config/mango/scripts/lib.sh"

CACHE="$STATE_DIR/weather.json"

# open-meteo's own publish cadence (`current.interval`). waybar polls at 300, so
# four calls in five are answered off disk — the poll is a floor, not a policy.
TTL=900

# Generated by modules/home/dotfiles.nix from `local.location`, so a transposed
# sign is an eval error. checks/static.sh asserts it reaches this file.
LOCATION_ENV="$MANGO_DIR/universal/weather-location.env"

API=https://api.open-meteo.com/v1/forecast

# Spelled as menus/control-center.sh spells it — same fact, two surfaces.
UNKNOWN='?'

# Also sourced inside fetch(); needed here for the place name on the cache-only
# path. Guarded, so the branch reporting the file missing can still run.
WEATHER_NAME=weather
if [ -r "$LOCATION_ENV" ]; then
	# shellcheck source=/dev/null
	. "$LOCATION_ENV"
fi

# One host, and it is the one answering the question — not noctalia's geocode
# indirection. docs/adr/0038.

# nf-weather, each checked with `fc-list ':charset=<hex>' family` against all
# three fonts the bar and the menus use. U+F6FF is why (gotchas.md -> rofi).
ICON_SUN=$'\uE30D'        # nf-weather-day_sunny
ICON_MOON=$'\uE32B'       # nf-weather-night_clear
ICON_SUN_CLOUD=$'\uE302'  # nf-weather-day_cloudy
ICON_MOON_CLOUD=$'\uE37E' # nf-weather-night_alt_cloudy
ICON_CLOUD=$'\uE312'      # nf-weather-cloudy
ICON_FOG=$'\uE313'        # nf-weather-fog
ICON_DRIZZLE=$'\uE35C'    # nf-weather-sprinkle
ICON_RAIN=$'\uE318'       # nf-weather-rain
ICON_SHOWERS=$'\uE319'    # nf-weather-showers
ICON_SNOW=$'\uE31A'       # nf-weather-snow
ICON_STORM=$'\uE31D'      # nf-weather-thunderstorm
ICON_HAIL=$'\uE314'       # nf-weather-hail
ICON_NA=$'\uE374'         # nf-weather-na

# WMO 4677, all 28 — enumerated off the table, not off the one value a test
# fetch returns. An unknown code says so rather than drawing "clear".
describe() {
	case "$1" in
	0) printf 'clear' ;;
	1) printf 'mainly clear' ;;
	2) printf 'partly cloudy' ;;
	3) printf 'overcast' ;;
	45) printf 'fog' ;;
	48) printf 'freezing fog' ;;
	51) printf 'light drizzle' ;;
	53) printf 'drizzle' ;;
	55) printf 'heavy drizzle' ;;
	56) printf 'freezing drizzle' ;;
	57) printf 'heavy freezing drizzle' ;;
	61) printf 'light rain' ;;
	63) printf 'rain' ;;
	65) printf 'heavy rain' ;;
	66) printf 'freezing rain' ;;
	67) printf 'heavy freezing rain' ;;
	71) printf 'light snow' ;;
	73) printf 'snow' ;;
	75) printf 'heavy snow' ;;
	77) printf 'snow grains' ;;
	80) printf 'light showers' ;;
	81) printf 'showers' ;;
	82) printf 'heavy showers' ;;
	85) printf 'light snow showers' ;;
	86) printf 'snow showers' ;;
	95) printf 'thunderstorm' ;;
	96) printf 'thunderstorm with hail' ;;
	99) printf 'thunderstorm with heavy hail' ;;
	*) printf 'unknown (code %s)' "$1" ;;
	esac
}

# Day/night differ only where the sky is visible. checks/static.sh asserts this
# covers the same codes describe() does — a phrase with no glyph draws na.
icon_for() {
	local code=$1 day=$2
	case "$code" in
	0) if [ "$day" = 1 ]; then printf '%s' "$ICON_SUN"; else printf '%s' "$ICON_MOON"; fi ;;
	1 | 2) if [ "$day" = 1 ]; then printf '%s' "$ICON_SUN_CLOUD"; else printf '%s' "$ICON_MOON_CLOUD"; fi ;;
	3) printf '%s' "$ICON_CLOUD" ;;
	45 | 48) printf '%s' "$ICON_FOG" ;;
	51 | 53 | 55 | 56 | 57) printf '%s' "$ICON_DRIZZLE" ;;
	61 | 63 | 65 | 66 | 67) printf '%s' "$ICON_RAIN" ;;
	71 | 73 | 75 | 77 | 85 | 86) printf '%s' "$ICON_SNOW" ;;
	80 | 81 | 82) printf '%s' "$ICON_SHOWERS" ;;
	95) printf '%s' "$ICON_STORM" ;;
	96 | 99) printf '%s' "$ICON_HAIL" ;;
	*) printf '%s' "$ICON_NA" ;;
	esac
}

# Refuses rather than defaults: `latitude=&longitude=` is a request open-meteo
# ANSWERS, with the weather at 0°N 0°E. gotchas.md -> Scripts.
load_location() {
	[ -r "$LOCATION_ENV" ] || return 1
	# shellcheck source=/dev/null
	. "$LOCATION_ENV"
	[ -n "${WEATHER_LAT:-}" ] && [ -n "${WEATHER_LON:-}" ]
}

# Atomic: `mv` after a complete write, so a killed fetch leaves the previous
# reading intact rather than a truncated file that renders `error` forever.
fetch() {
	local tmp out
	load_location || return 1
	mkdir -p "$STATE_DIR" || return 1
	tmp=$(mktemp "$CACHE.XXXXXX") || return 1

	# --fail so an error body is not cached as a reading; --max-time because
	# waybar runs this exec synchronously.
	out=$(curl -sS --fail --max-time 10 --get "$API" \
		--data-urlencode "latitude=$WEATHER_LAT" \
		--data-urlencode "longitude=$WEATHER_LON" \
		--data-urlencode "current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,is_day,wind_speed_10m" \
		--data-urlencode "daily=temperature_2m_max,temperature_2m_min" \
		--data-urlencode "timezone=auto" \
		--data-urlencode "forecast_days=1" 2>/dev/null) || {
		rm -f "$tmp"
		return 1
	}

	# A captive portal answers 200 with HTML, and HTML in the cache is a
	# reading that never expires and never parses.
	jq -e '.current.temperature_2m != null' >/dev/null 2>&1 <<<"$out" || {
		rm -f "$tmp"
		return 1
	}

	printf '%s\n' "$out" >"$tmp" && mv "$tmp" "$CACHE"
}

cache_age() {
	local mtime now
	mtime=$(stat -c %Y "$CACHE" 2>/dev/null) || return 1
	now=$(date +%s)
	printf '%s' "$((now - mtime))"
}

# Whole minutes, then hours — "4271 seconds old" is a number you have to do
# arithmetic on.
human_age() {
	local s=$1
	if [ "$s" -lt 120 ]; then
		printf '%ss' "$s"
	elif [ "$s" -lt 3600 ]; then
		printf '%smin' "$((s / 60))"
	else
		printf '%sh %smin' "$((s / 3600))" "$(((s % 3600) / 60))"
	fi
}

# `alt` is waybar's own key, unused when `format` is "{}", so it carries the
# phrase the control-centre row wants as a FIELD. Cutting it out of the tooltip
# instead rendered "light" for "light drizzle" — gotchas.md -> Waybar.
emit() {
	jq -cn --arg text "$1" --arg alt "$2" --arg cls "$3" --arg tip "$4" \
		'{text: $text, alt: $alt, class: $cls, tooltip: $tip}'
}

render() {
	local cls=$1 age=$2 fields code day temp feels hum wind hi lo icon desc tip

	# One jq, joined on U+001F — `read` with IFS=$'\t' cannot see an empty
	# leading field, and any of these can be null. gotchas.md -> Scripts.
	fields=$(jq -r '[
		.current.weather_code, .current.is_day, .current.temperature_2m,
		.current.apparent_temperature, .current.relative_humidity_2m,
		.current.wind_speed_10m,
		.daily.temperature_2m_max[0], .daily.temperature_2m_min[0]
	] | map(. // "" | tostring) | join("\u001f")' "$CACHE" 2>/dev/null) || {
		emit "$ICON_NA $UNKNOWN" "the cache is unreadable" error "Weather: the cache is unreadable"
		return
	}
	IFS=$'\037' read -r code day temp feels hum wind hi lo <<<"$fields"

	[ -n "$code" ] && [ -n "$temp" ] || {
		emit "$ICON_NA $UNKNOWN" "the cached reading has no temperature in it" error \
			"Weather: the cached reading has no temperature in it"
		return
	}

	icon=$(icon_for "$code" "${day:-1}")
	desc=$(describe "$code")

	# The bar rounds; the tooltip keeps the decimal.
	tip="$WEATHER_NAME — $desc"
	tip+=$'\n'"Now ${temp}°C"
	[ -n "$feels" ] && [ "$feels" != "$temp" ] && tip+=" (feels ${feels}°C)"
	[ -n "$hi" ] && [ -n "$lo" ] && tip+=$'\n'"Today ${lo}–${hi}°C"
	[ -n "$hum" ] && tip+=$'\n'"Humidity ${hum}%"
	[ -n "$wind" ] && tip+=$'\n'"Wind ${wind} km/h"

	# The age is the whole point of the class, so it goes in both the tooltip
	# and `alt` — the control-centre row sees only `alt`.
	if [ "$cls" = stale ]; then
		desc+=" · $(human_age "$age") old"
		tip+=$'\n'"Stale — last fetched $(human_age "$age") ago"
	fi

	emit "$icon $(printf '%.0f' "$temp")°C" "$desc" "$cls" "$tip"
}

do_status() {
	local age
	age=$(cache_age) || age=""

	if [ -n "$age" ] && [ "$age" -lt "$TTL" ]; then
		render ok "$age"
		return
	fi

	if fetch; then
		render ok 0
		return
	fi

	# Serve what there is, labelled — or say there is nothing, which is a
	# different sentence.
	if [ -n "$age" ]; then
		render stale "$age"
	elif [ -r "$LOCATION_ENV" ]; then
		emit "$ICON_NA $UNKNOWN" "no reading yet, and open-meteo is unreachable" error \
			"Weather: no reading yet and open-meteo is unreachable"
	else
		# A rebuild fixes this one, not a network — so it says so.
		emit "$ICON_NA $UNKNOWN" "coordinates missing — rebuild" error \
			"Weather: coordinates missing — weather-location.env is not in the generation"
	fi
}

# The control centre's row: cache only, never a socket, whatever the age. In
# `minimal` no bar module keeps the cache warm, so `stale` is this row's
# ordinary state there — and Enter is one press from a current one.
do_read() {
	local age
	age=$(cache_age) || {
		emit "$ICON_NA $UNKNOWN" "no reading cached — press Enter to fetch one" error \
			"Weather: no reading cached — press Enter to fetch one"
		return
	}
	if [ "$age" -lt "$TTL" ]; then
		render ok "$age"
	else
		render stale "$age"
	fi
}

# Forced, past the TTL — the only path that ignores the cache. Reached by Enter
# on the control-centre row AND by a click on the bar module.
#
# SAYS SO WHEN IT FAILS. With no cache behind it the row re-renders identically,
# which is the "action that appears to do nothing" menus/control-center.sh
# refuses to have. The two failures need different sentences: one is a network,
# the other is a rebuild.
do_refresh() {
	if ! fetch; then
		if [ -r "$LOCATION_ENV" ]; then
			notify-send "Weather" "open-meteo unreachable — the reading is unchanged"
		else
			notify-send -u critical "Weather" \
				"No coordinates — weather-location.env is not in the generation"
		fi
	fi
	# The bar is the other reader. Must match `signal` on custom/weather in
	# modules/home/waybar.nix; checks/static.sh asserts the two agree.
	pkill -RTMIN+13 waybar 2>/dev/null || true
}

case "${1:-status}" in
status) do_status ;;
read) do_read ;;
refresh) do_refresh ;;
*)
	echo "Usage: $0 <status|read|refresh>"
	exit 1
	;;
esac
