#!/usr/bin/env bash
# Usage: weather.sh <status|read|refresh|open|panel>
#
# The one owner of "what the weather is" here; custom/weather and the
# control-centre row are both readers. docs/adr/0038.
#
#   status   the bar        fetches when the cache has expired
#   read     the menu row   cache only, never a socket — that render is parallel
#                           and costs its slowest row (73 ms). Asserted.
#   refresh  Ctrl+Enter,    fetches past the ttl. Nothing to signal: wayle
#            middle-click   re-reads through `on-action` (docs/adr/0045)
#   open     right-click    hands the coordinates to a browser. No network of
#                           its own, and no reader — it renders nothing.
#   panel    SUPER+CTRL+w,  the detailed reading, in rofi. Replaced wayle's
#            bar left-click  `dropdown:weather` on 2026-08-26 — docs/adr/0050.
#
# Three classes, because a served cache that does not say it is one is
# yesterday's temperature in today's font: `ok`, `stale` (greyed, with its age)
# and `error` (`?`, never a number).

set -u

. "$HOME/.config/mango/scripts/lib.sh"

CACHE="$STATE_DIR/weather.json"

# open-meteo's own publish cadence (`current.interval`). waybar polls at 300, so
# four calls in five are answered off disk — the poll is a floor, not a policy.
TTL=900

# Generated by modules/home/dotfiles.nix from `local.location`, so a transposed
# sign is an eval error. checks/static.sh asserts it reaches this file.
LOCATION_ENV="$MANGO_DIR/universal/weather-location.env"

API=https://api.open-meteo.com/v1/forecast

# Spelled as menus/control-center.sh spells it — same fact, two surfaces.
UNKNOWN='?'

# Also sourced inside fetch(); needed here for the place name on the cache-only
# path. Guarded, so the branch reporting the file missing can still run.
WEATHER_NAME=weather
if [ -r "$LOCATION_ENV" ]; then
	# shellcheck source=/dev/null
	. "$LOCATION_ENV"
fi

# One host, and it is the one answering the question — not noctalia's geocode
# indirection. docs/adr/0038.

# nf-weather, each checked with `fc-list ':charset=<hex>' family` against all
# three fonts the bar and the menus use. U+F6FF is why (gotchas.md -> rofi).
ICON_SUN=$'\uE30D'        # nf-weather-day_sunny
ICON_MOON=$'\uE32B'       # nf-weather-night_clear
ICON_SUN_CLOUD=$'\uE302'  # nf-weather-day_cloudy
ICON_MOON_CLOUD=$'\uE37E' # nf-weather-night_alt_cloudy
ICON_CLOUD=$'\uE312'      # nf-weather-cloudy
ICON_FOG=$'\uE313'        # nf-weather-fog
ICON_DRIZZLE=$'\uE35C'    # nf-weather-sprinkle
ICON_RAIN=$'\uE318'       # nf-weather-rain
ICON_SHOWERS=$'\uE319'    # nf-weather-showers
ICON_SNOW=$'\uE31A'       # nf-weather-snow
ICON_STORM=$'\uE31D'      # nf-weather-thunderstorm
ICON_HAIL=$'\uE314'       # nf-weather-hail
ICON_NA=$'\uE374'         # nf-weather-na

# WMO 4677, all 28 — enumerated off the table, not off the one value a test
# fetch returns. An unknown code says so rather than drawing "clear".
describe() {
	case "$1" in
	0) printf 'clear' ;;
	1) printf 'mainly clear' ;;
	2) printf 'partly cloudy' ;;
	3) printf 'overcast' ;;
	45) printf 'fog' ;;
	48) printf 'freezing fog' ;;
	51) printf 'light drizzle' ;;
	53) printf 'drizzle' ;;
	55) printf 'heavy drizzle' ;;
	56) printf 'freezing drizzle' ;;
	57) printf 'heavy freezing drizzle' ;;
	61) printf 'light rain' ;;
	63) printf 'rain' ;;
	65) printf 'heavy rain' ;;
	66) printf 'freezing rain' ;;
	67) printf 'heavy freezing rain' ;;
	71) printf 'light snow' ;;
	73) printf 'snow' ;;
	75) printf 'heavy snow' ;;
	77) printf 'snow grains' ;;
	80) printf 'light showers' ;;
	81) printf 'showers' ;;
	82) printf 'heavy showers' ;;
	85) printf 'light snow showers' ;;
	86) printf 'snow showers' ;;
	95) printf 'thunderstorm' ;;
	96) printf 'thunderstorm with hail' ;;
	99) printf 'thunderstorm with heavy hail' ;;
	*) printf 'unknown (code %s)' "$1" ;;
	esac
}

# Day/night differ only where the sky is visible. checks/static.sh asserts this
# covers the same codes describe() does — a phrase with no glyph draws na.
icon_for() {
	local code=$1 day=$2
	case "$code" in
	0) if [ "$day" = 1 ]; then printf '%s' "$ICON_SUN"; else printf '%s' "$ICON_MOON"; fi ;;
	1 | 2) if [ "$day" = 1 ]; then printf '%s' "$ICON_SUN_CLOUD"; else printf '%s' "$ICON_MOON_CLOUD"; fi ;;
	3) printf '%s' "$ICON_CLOUD" ;;
	45 | 48) printf '%s' "$ICON_FOG" ;;
	51 | 53 | 55 | 56 | 57) printf '%s' "$ICON_DRIZZLE" ;;
	61 | 63 | 65 | 66 | 67) printf '%s' "$ICON_RAIN" ;;
	71 | 73 | 75 | 77 | 85 | 86) printf '%s' "$ICON_SNOW" ;;
	80 | 81 | 82) printf '%s' "$ICON_SHOWERS" ;;
	95) printf '%s' "$ICON_STORM" ;;
	96 | 99) printf '%s' "$ICON_HAIL" ;;
	*) printf '%s' "$ICON_NA" ;;
	esac
}

# Refuses rather than defaults: `latitude=&longitude=` is a request open-meteo
# Answers, with the weather at 0°N 0°E. gotchas.md -> Scripts.
load_location() {
	[ -r "$LOCATION_ENV" ] || return 1
	# shellcheck source=/dev/null
	. "$LOCATION_ENV"
	[ -n "${WEATHER_LAT:-}" ] && [ -n "${WEATHER_LON:-}" ]
}

# Atomic: `mv` after a complete write, so a killed fetch leaves the previous
# reading intact rather than a truncated file that renders `error` forever.
#
# One request carries the whole tooltip. Every field asked for here is read by
# render() and every field render() reads is asked for here — checks/static.sh
# asserts both directions, because a name dropped from this URL is one tooltip
# line that stops rendering while the six around it stay right.
fetch() {
	local tmp out hist now
	load_location || return 1
	mkdir -p "$STATE_DIR" || return 1
	tmp=$(mktemp "$CACHE.XXXXXX") || return 1

	# --fail so an error body is not cached as a reading; --max-time because
	# waybar runs this exec synchronously.
	out=$(curl -sS --fail --max-time 10 --get "$API" \
		--data-urlencode "latitude=$WEATHER_LAT" \
		--data-urlencode "longitude=$WEATHER_LON" \
		--data-urlencode "current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,is_day,wind_speed_10m,wind_direction_10m,pressure_msl" \
		--data-urlencode "hourly=temperature_2m,precipitation_probability,weather_code,is_day" \
		--data-urlencode "daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset,uv_index_max" \
		--data-urlencode "timezone=auto" \
		--data-urlencode "forecast_days=5" 2>/dev/null) || {
		rm -f "$tmp"
		return 1
	}

	# A captive portal answers 200 with HTML, and HTML in the cache is a
	# reading that never expires and never parses.
	jq -e '.current.temperature_2m != null' >/dev/null 2>&1 <<<"$out" || {
		rm -f "$tmp"
		return 1
	}

	# The trend is the one fact a single response cannot carry, so the cache
	# keeps six hours of pressure samples and render() compares against one
	# about three hours old. The cache is therefore not the response verbatim.
	# Fewer than two hours apart, no trend is claimed and the line stops at the
	# reading — a trend computed over fifteen minutes is noise wearing an arrow.
	now=$(date +%s)
	hist=$(jq -c '[.history[]? | select(.t != null and .p != null)]' "$CACHE" 2>/dev/null) || hist=""
	[ -n "$hist" ] || hist='[]'
	out=$(jq -c --argjson h "$hist" --argjson now "$now" \
		'.history = (($h + [{t: $now, p: .current.pressure_msl}])
			| map(select(.p != null and ($now - .t) <= 21600)))' <<<"$out") || {
		rm -f "$tmp"
		return 1
	}

	printf '%s\n' "$out" >"$tmp" && mv "$tmp" "$CACHE"
}

cache_age() {
	local mtime now
	mtime=$(stat -c %Y "$CACHE" 2>/dev/null) || return 1
	now=$(date +%s)
	printf '%s' "$((now - mtime))"
}

# Whole minutes, then hours — "4271 seconds old" is a number you have to do
# arithmetic on.
human_age() {
	local s=$1
	if [ "$s" -lt 120 ]; then
		printf '%ss' "$s"
	elif [ "$s" -lt 3600 ]; then
		printf '%smin' "$((s / 60))"
	else
		printf '%sh %smin' "$((s / 3600))" "$(((s % 3600) / 60))"
	fi
}

# Eight points from a bearing. `wind_direction_10m` is where the wind comes
# From, which is why the line printing this says "from": an arrow has to pick a
# convention and half the world reads it the other way.
compass() {
	local deg=${1%%.*}
	[ -n "$deg" ] || return 0
	# Doubled, so the boundaries land on 22.5° exactly rather than on 23.
	case $(((deg * 2 + 45) % 720 / 90)) in
	0) printf 'N' ;;
	1) printf 'NE' ;;
	2) printf 'E' ;;
	3) printf 'SE' ;;
	4) printf 'S' ;;
	5) printf 'SW' ;;
	6) printf 'W' ;;
	7) printf 'NW' ;;
	esac
}

# WHO's five bands. A bare UV number means nothing to anyone, and the bands are
# defined on the value, so this truncates — rounding puts 2.75 in `moderate`,
# which is the band above the one it is in.
uv_band() {
	local n=${1%%.*}
	[ -n "$n" ] || return 0
	if [ "$n" -lt 3 ]; then
		printf 'low'
	elif [ "$n" -lt 6 ]; then
		printf 'moderate'
	elif [ "$n" -lt 8 ]; then
		printf 'high'
	elif [ "$n" -lt 11 ]; then
		printf 'very high'
	else
		printf 'extreme'
	fi
}

# From two "yyyy-mm-ddthh:mm" strings, in human_age's units so the tooltip reads
# in one system. `10#` because 08 and 09 are not octal numbers.
day_length() {
	local a=$1 b=$2 m
	m=$((10#${b:11:2} * 60 + 10#${b:14:2} - (10#${a:11:2} * 60 + 10#${a:14:2})))
	[ "$m" -lt 0 ] && m=$((m + 1440))
	printf '%sh %smin' "$((m / 60))" "$((m % 60))"
}

# waybar sets a custom module's tooltip with set_tooltip_markup, so a bare `&`
# in the place name is invalid Pango and the tooltip does not appear at all —
# not "appears wrong". The place name is the only value here that comes from
# outside this script.
esc() {
	local s=${1//&/&amp;}
	printf '%s' "${s//</&lt;}"
}

# `alt` is waybar's own key, unused when `format` is "{}", so it carries the
# phrase the control-centre row wants as a field. Cutting it out of the tooltip
# instead rendered "light" for "light drizzle" — gotchas.md -> Waybar.
emit() {
	jq -cn --arg text "$1" --arg alt "$2" --arg cls "$3" --arg tip "$4" \
		'{text: $text, alt: $alt, class: $cls, tooltip: $tip}'
}

# ── The reading, once ─────────────────────────────────────────────────────
#
# The bar's tooltip, the control-centre row and the rofi panel are three
# renderings of ONE read, so the jq lives here rather than in each of them.
#
# One jq for every field any surface shows: joined on U+001F inside a block and
# U+001E between the three, because `read` with IFS=$'\t' cannot see an empty
# leading field and any of these can be null. gotchas.md -> Scripts. The
# separators arrive as arguments so this file carries no control bytes.
#
# EIGHT hourly picks, at two-hour steps: the panel shows all of them and the
# tooltip every other one, which is the only difference between the two. Four
# was the tooltip's whole forecast until 2026-08-26 and is a thin panel.
#
# Returns 1 on an unreadable cache and 2 on one with no temperature in it —
# two numbers because they need two sentences, and only one caller answers in
# JSON.
W_HOURLY=""
W_DAILY=""
load_reading() {
	local blob rest fields
	blob=$(jq -r --arg us $'\037' --arg rs $'\036' --argjson now "$(date +%s)" '
		def s: . // "" | tostring;
		def j: join($us);
		. as $w
		| ($w.current.time // "") as $t0
		| ([range(0; ($w.hourly.time // [] | length))
		    | select($w.hourly.time[.] > $t0)]) as $fut
		| ([$fut[0], $fut[2], $fut[4], $fut[6],
		    $fut[8], $fut[10], $fut[12], $fut[14]]
		   | map(select(. != null))) as $pick
		| (($w.history // [])
		   | map(select(.t != null and .p != null
		         and ($now - .t) >= 7200 and ($now - .t) <= 21600))
		   | sort_by((($now - .t) - 10800) | length) | first) as $ref
		| [([$w.current.weather_code, $w.current.is_day, $w.current.temperature_2m,
		     $w.current.apparent_temperature, $w.current.relative_humidity_2m,
		     $w.current.wind_speed_10m, $w.current.wind_direction_10m,
		     $w.current.pressure_msl,
		     $w.daily.temperature_2m_max[0], $w.daily.temperature_2m_min[0],
		     $w.daily.precipitation_probability_max[0], $w.daily.uv_index_max[0],
		     $w.daily.sunrise[0], $w.daily.sunset[0],
		     (if $ref == null or $w.current.pressure_msl == null then null
		      else (($w.current.pressure_msl - $ref.p) * 10 | round) end),
		     (if $ref == null then null else ($now - $ref.t) end)] | map(s) | j),
		   ($pick | map(. as $i |
		      [$w.hourly.time[$i][11:16],
		       ($w.hourly.weather_code[$i] | s), ($w.hourly.is_day[$i] | s),
		       ($w.hourly.temperature_2m[$i] | s),
		       ($w.hourly.precipitation_probability[$i] | s)] | j) | join("\n")),
		   ([range(1; ($w.daily.time // [] | length))] | map(. as $i |
		      [(($w.daily.time[$i] + "T12:00:00Z")
		        | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime | strftime("%a")),
		       ($w.daily.weather_code[$i] | s), ($w.daily.temperature_2m_max[$i] | s),
		       ($w.daily.temperature_2m_min[$i] | s),
		       ($w.daily.precipitation_probability_max[$i] | s)] | j) | join("\n"))]
		| join($rs)
	' "$CACHE" 2>/dev/null) || return 1

	# Split by hand, not with `read`: both forecast blocks contain newlines and
	# `read` stops at the first one.
	rest=$blob
	fields=${rest%%$'\036'*}
	rest=${rest#*$'\036'}
	W_HOURLY=${rest%%$'\036'*}
	W_DAILY=${rest#*$'\036'}

	IFS=$'\037' read -r code day temp feels hum wind wdir press hi lo pop uv \
		sunrise sunset ptenths page <<<"$fields"

	[ -n "$code" ] && [ -n "$temp" ] || return 2
}

# The block under the headline. Shared, because the tooltip and the panel differ
# only in the line ABOVE it: one leads with "Now 18.2°C", the other with the
# same number at three times the size.
detail_lines() {
	local out="" abs dir
	if [ -n "$hi" ] && [ -n "$lo" ]; then
		out+="Today ${lo}–${hi}°C"
		[ -n "$pop" ] && out+=" · rain ${pop}%"
		out+=$'\n'
	fi
	[ -n "$hum" ] && out+="Humidity ${hum}%"$'\n'
	# One decimal, and the band read off that figure rather than the raw one, so
	# the word and the number cannot disagree at a boundary.
	if [ -n "$uv" ]; then
		uv=$(printf '%.1f' "$uv")
		out+="UV $uv ($(uv_band "$uv"))"$'\n'
	fi
	if [ -n "$wind" ]; then
		out+="Wind ${wind} km/h"
		[ -n "$wdir" ] && out+=" from $(compass "$wdir")"
		out+=$'\n'
	fi
	if [ -n "$press" ]; then
		out+="Pressure ${press} hPa"
		# Tenths, as an integer, so nothing here has to do arithmetic on a float.
		# Under 1 hPa over three hours is `steady` — the word the number would
		# otherwise invite you to over-read.
		if [ -n "$ptenths" ] && [ -n "$page" ]; then
			abs=${ptenths#-}
			if [ "$abs" -lt 10 ]; then
				out+=" · steady"
			else
				if [ "$ptenths" = "$abs" ]; then dir=rising; else dir=falling; fi
				out+=" · $dir $((abs / 10)).$((abs % 10)) in $(human_age "$page")"
			fi
		fi
		out+=$'\n'
	fi
	[ -n "$sunrise" ] && [ -n "$sunset" ] &&
		out+="Sun ${sunrise:11:5} – ${sunset:11:5} · $(day_length "$sunrise" "$sunset")"$'\n'
	printf '%s' "$out"
}

# ONE column layout for the hourly rows and the daily ones, so the panel can
# print them as a single list and they still line up. bash's printf pads by
# CHARACTERS under a UTF-8 locale, not bytes, so the en-dash in a daily range
# costs the column nothing — checked, because the reverse was written here until
# 2026-08-26 and the two blocks only ever appeared separately.
fc_row() {
	printf '%-5s %s %9s %5s\n' "$1" "$2" "$3" "$4"
}

# `hour_rows 2` is every other pick — the tooltip's four. No argument is all
# eight, which is the panel's.
hour_rows() {
	local step=${1:-1} i=0 t hcode hday htemp hpop
	[ -n "$W_HOURLY" ] || return 0
	while IFS=$'\037' read -r t hcode hday htemp hpop; do
		[ -n "$t" ] || continue
		if [ $((i % step)) -eq 0 ]; then
			[ -n "$htemp" ] && htemp=$(printf '%.0f°C' "$htemp")
			[ -n "$hpop" ] && hpop="$hpop%"
			fc_row "$t" "$(icon_for "$hcode" "${hday:-1}")" "$htemp" "$hpop"
		fi
		i=$((i + 1))
	done <<<"$W_HOURLY"
}

day_rows() {
	local dname dcode dhi dlo dpop rng
	[ -n "$W_DAILY" ] || return 0
	while IFS=$'\037' read -r dname dcode dhi dlo dpop; do
		[ -n "$dname" ] || continue
		rng=""
		[ -n "$dlo" ] && [ -n "$dhi" ] && rng=$(printf '%.0f–%.0f°C' "$dlo" "$dhi")
		[ -n "$dpop" ] && dpop="$dpop%"
		fc_row "$dname" "$(icon_for "$dcode" 1)" "$rng" "$dpop"
	done <<<"$W_DAILY"
}

render() {
	local cls=$1 age=$2 icon desc tip block rc

	load_reading
	rc=$?
	if [ "$rc" -eq 1 ]; then
		emit "$ICON_NA $UNKNOWN" "the cache is unreadable" error "Weather: the cache is unreadable"
		return
	fi
	if [ "$rc" -eq 2 ]; then
		emit "$ICON_NA $UNKNOWN" "the cached reading has no temperature in it" error \
			"Weather: the cached reading has no temperature in it"
		return
	fi

	icon=$(icon_for "$code" "${day:-1}")
	desc=$(describe "$code")

	# The bar rounds; the tooltip keeps the decimal. The forecast rows round as
	# well — a column of one-decimal temperatures is four characters of noise
	# per line.
	tip="$(esc "$WEATHER_NAME") — $desc"
	tip+=$'\n'"Now ${temp}°C"
	[ -n "$feels" ] && [ "$feels" != "$temp" ] && tip+=" (feels ${feels}°C)"
	block=$(detail_lines)
	[ -n "$block" ] && tip+=$'\n'"$block"
	block=$(hour_rows 2)
	[ -n "$block" ] && tip+=$'\n\n'"$block"
	block=$(day_rows)
	[ -n "$block" ] && tip+=$'\n\n'"$block"

	# The age is the whole point of the class, so it goes in both the tooltip
	# and `alt` — the control-centre row sees only `alt`.
	if [ "$cls" = stale ]; then
		desc+=" · $(human_age "$age") old"
		tip+=$'\n\n'"Stale — last fetched $(human_age "$age") ago"
	fi

	emit "$icon $(printf '%.0f' "$temp")°C" "$desc" "$cls" "$tip"
}

do_status() {
	local age
	age=$(cache_age) || age=""

	if [ -n "$age" ] && [ "$age" -lt "$TTL" ]; then
		render ok "$age"
		return
	fi

	if fetch; then
		render ok 0
		return
	fi

	# Serve what there is, labelled — or say there is nothing, which is a
	# different sentence.
	if [ -n "$age" ]; then
		render stale "$age"
	elif [ -r "$LOCATION_ENV" ]; then
		emit "$ICON_NA $UNKNOWN" "no reading yet, and open-meteo is unreachable" error \
			"Weather: no reading yet and open-meteo is unreachable"
	else
		# A rebuild fixes this one, not a network — so it says so.
		emit "$ICON_NA $UNKNOWN" "coordinates missing — rebuild" error \
			"Weather: coordinates missing — weather-location.env is not in the generation"
	fi
}

# The control centre's row: cache only, never a socket, whatever the age. In
# `minimal` no bar module keeps the cache warm, so `stale` is this row's
# ordinary state there — and Enter is one press from a current one.
do_read() {
	local age
	age=$(cache_age) || {
		emit "$ICON_NA $UNKNOWN" "no reading cached — press Enter to fetch one" error \
			"Weather: no reading cached — press Enter to fetch one"
		return
	}
	if [ "$age" -lt "$TTL" ]; then
		render ok "$age"
	else
		render stale "$age"
	fi
}

# Forced, past the ttl — the only path that ignores the cache. Reached by
# Ctrl+Enter on the control-centre row and by a MIDDLE click on the bar module —
# left-click opens wayle's panel now (docs/adr/0046).
#
# Says so when it fails. With no cache behind it the row re-renders identically,
# which is the "action that appears to do nothing" menus/control-center.sh
# refuses to have. The two failures need different sentences: one is a network,
# the other is a rebuild.
do_refresh() {
	if ! fetch; then
		if [ -r "$LOCATION_ENV" ]; then
			notify-send "Weather" "open-meteo unreachable — the reading is unchanged"
		else
			notify-send -u critical "Weather" \
				"No coordinates — weather-location.env is not in the generation"
		fi
	fi
	# THE BAR PUSH IS BACK. waybar takes RTMIN+n and custom/weather declares
	# `signal = 13`; wayle took no signal, so this line was removed on
	# 2026-08-24 and the refresh was invisible until the next 300 s poll.
	# docs/adr/0051, reversing that half of docs/adr/0045.
	#
	# `|| true` because this also runs in noctalia mode, where there is no
	# waybar: pkill matching nothing returns 1, and a refresh that worked would
	# exit non-zero. That is docs/adr/0047's finding, one script over.
	pkill -RTMIN+13 waybar 2>/dev/null || true
}

# The way out to a page no tooltip can hold. Reached by a right-click on the
# bar and by the control centre's second weather row.
#
# The URL is `local.location.forecastUrl`, not a constant here: which site it is
# decides who besides open-meteo learns where this machine is, and that belongs
# next to the coordinates. docs/adr/0044.
#
# `setsid -f` because both callers wait on this and xdg-open waits on the
# browser when one is not already running — the control-centre loop would hang
# until Zen exits. The exit status goes with it, so the two failures worth a
# sentence are checked before the fork, and the third (a mime association
# pointing at a .desktop that is not installed, which silently opens some other
# browser) is asserted by checks/static.sh instead.
do_open() {
	if [ -z "${WEATHER_URL:-}" ]; then
		notify-send -u critical "Weather" \
			"No forecast URL — weather-location.env is not in the generation"
		return 1
	fi
	command -v xdg-open >/dev/null 2>&1 || {
		notify-send -u critical "Weather" "xdg-open is not on PATH"
		return 1
	}
	setsid -f xdg-open "$WEATHER_URL" >/dev/null 2>&1
}

# ── The panel ─────────────────────────────────────────────────────────────
#
# rofi, not a wayle dropdown. `dropdown:weather` is one of ten types wayle
# defines internally and a script cannot add an eleventh, so the detailed
# reading was the one surface on this machine drawn by something other than the
# menus — and the bar click was the only way in, since com.wayle.Shell1 exposes
# BarShow/BarHide/BarToggle and nothing that opens a dropdown. docs/adr/0050.
#
# `status`'s freshness ladder rather than `read`'s: this is a foreground surface
# somebody just asked for, so it can afford the socket the control-centre row
# cannot (docs/adr/0038).
#
# THE TWO KEYS ARE NOT IN A `-mesg` HINT. A standing line of instructions above
# a surface whose point is to report is the panel explaining itself; the same
# hint went into menus/control-center.sh on 2026-08-24 and came out the same
# day. They are in docs/SYSTEM.md §8.
do_panel() {
	local force=0 age cls icon desc mesg block
	local -a rows

	while :; do
		age=$(cache_age) || age=""
		# At most one fetch per pass: when the cache has expired, and when
		# Ctrl+Enter asked past it.
		if [ "$force" -eq 1 ] || [ -z "$age" ] || [ "$age" -ge "$TTL" ]; then
			if fetch; then
				age=0
			elif [ "$force" -eq 1 ]; then
				notify-send "Weather" "open-meteo unreachable — the reading is unchanged"
			fi
			force=0
		fi

		# Nothing cached and nothing fetched. A rebuild fixes one of these and a
		# network the other, so they are two sentences — do_status's pair, said
		# through notify-send because this surface has no error row to draw them in.
		if [ -z "$age" ]; then
			if [ -r "$LOCATION_ENV" ]; then
				notify-send -u critical "Weather" \
					"No reading yet and open-meteo is unreachable"
			else
				notify-send -u critical "Weather" \
					"No coordinates — weather-location.env is not in the generation"
			fi
			return 1
		fi

		if [ "$age" -lt "$TTL" ]; then cls=ok; else cls=stale; fi

		load_reading || {
			notify-send -u critical "Weather" "The cached reading is unusable"
			return 1
		}

		icon=$(icon_for "$code" "${day:-1}")
		desc=$(describe "$code")

		# `-mesg` is Pango markup ALWAYS, so the place name goes through esc() —
		# the same reason the tooltip has one, and it is still the only value here
		# that comes from outside this script.
		#
		# NO COLOUR IN THE MARKUP. rofi's colours come from the generated
		# colors.rasi, and a hex code here would be a sixth copy of the palette
		# with nothing holding it in step (docs/adr/0009). Size and weight only.
		mesg="<span size=\"xx-large\">$icon  $(printf '%.0f' "$temp")°C</span>"
		mesg+=$'\n'"<b>$(esc "$WEATHER_NAME")</b> — $desc"
		[ -n "$feels" ] && [ "$feels" != "$temp" ] &&
			mesg+=" · feels $(printf '%.0f' "$feels")°C"
		block=$(detail_lines)
		[ -n "$block" ] && mesg+=$'\n'"$block"
		[ "$cls" = stale ] && mesg+=$'\n'"Stale — last fetched $(human_age "$age") ago"

		mapfile -t rows < <(
			hour_rows
			day_rows
		)

		# rofi's exit status IS the keybinding, and it is the only thing that tells
		# two accept keys apart: Enter, Shift+Enter and Ctrl+Enter all exit 0 on
		# their own bindings, and only a `-kb-custom-N` becomes 10 + n. The default
		# `Control+Return` has to be unset first or rofi draws "already bound" as an
		# error dialog where the panel should be. docs/gotchas.md -> rofi.
		#
		# The row count is passed exactly: `lines` is a fixed height the theme takes
		# from the command line, so the shared ceiling would page a fixed set.
		# Discarded, not captured: every row does the same thing, so the STATUS is
		# the whole answer and there is nothing to dispatch on.
		printf '%s\n' "${rows[@]}" |
			rofi_menu "${#rows[@]}" -no-custom -p "Weather" -mesg "$mesg" \
				-kb-accept-custom "" -kb-custom-1 "Control+Return" >/dev/null
		case $? in
		0)
			# No inert row anywhere in the list, because Enter does the same thing
			# on all of them: this is a readout, and both verbs act on the panel
			# rather than on whichever row happened to be selected.
			do_open
			return 0
			;;
		10) force=1 ;;
		*) return 0 ;;
		esac
	done
}

case "${1:-status}" in
status) do_status ;;
read) do_read ;;
refresh) do_refresh ;;
open) do_open ;;
panel) do_panel ;;
*)
	echo "Usage: $0 <status|read|refresh|open|panel>"
	exit 1
	;;
esac
