color=282828
font=monospace
indicator-radius=80
indicator-thickness=8
ring-color=d79921
key-highlight-color=d79921ff
inside-color=282828ff
line-color=282828ff
separator-color=00000000
text-color=ebdbb2ff
ring-ver-color=b8bb26ff
inside-ver-color=282828ff
ring-wrong-color=fb4934ff
inside-wrong-color=282828ff
ring-clear-color=83a598ff
inside-clear-color=282828ff
