bind=Super,C,spawn,dms ipc call control-center toggle
bind=Super+Ctrl,Delete,spawn,dms ipc call powermenu toggle
bind=Super+Ctrl,N,spawn,dms ipc call notepad toggle
bind=Super,Delete,spawn,dms ipc call lock lock
bind=Super+Shift,S,spawn,dms ipc call lock lock
