# DMS mode
source=./universal/settings.conf
source=./universal/bind.conf
source=./universal/rule.conf
source=./universal/monitor.conf
source=./universal/tag.conf
source=./universal/autostart.conf
source=./dms/autostart.conf

animations=1
layer_animations=1
border_radius=6
no_radius_when_single=0
no_border_when_single=0
smartgaps=0

source=./dms/colors.conf
source=./dms/layout.conf
source=./dms/outputs.conf
source=./dms/cursor.conf
source=./dms/binds.conf

bind=SUPER,space,spawn,dms ipc call spotlight toggle
bind=SUPER,numbersign,spawn,dms ipc call settings toggle
bind=SUPER,v,spawn_shell,dms ipc call clipboard toggle
bind=CTRL+ALT,backslash,spawn_shell,dms ipc call notifications toggle
bind=CTRL+ALT,BackSpace,spawn_shell,dms ipc call notifications clearAll
bind=SUPER+SHIFT,comma,spawn_shell,dms ipc call settings toggle
