# Hand-written dotfiles, linked into ~/.config.
#
# Three tiers, best first: GENERATED by a home-manager module (programs.nix,
# waybar.nix), STORE-BASED (`source = ../../dotfiles/X`), and OUT-OF-STORE
# (`link "X"`, a live symlink into the checkout). Generated is the default;
# out-of-store is corectrl only. See docs/adr/0009 for the rule and docs/adr/0002
# for why out-of-store was once unavoidable.
{
  config,
  pkgs,
  lib,
  ...
}:

let
  # Must not be ~/.config: `xdg.configFile.<name>` writes *to* ~/.config/<name>,
  # so pointing this at ~/.config makes every entry a symlink to itself, and
  # `backupFileExtension` turns that into a dangling link with no error.
  # Declared in options.nix because shell.nix's rebuild aliases need it too.
  dots = config.local.checkout;
  link = path: config.lib.file.mkOutOfStoreSymlink "${dots}/dotfiles/${path}";
in
{
  xdg.configFile = {
    # --- Desktop environment ------------------------------------------------
    # `recursive` is load-bearing: the mode scripts must be able to create
    # config.conf inside this directory, which a plain `source` (one symlink to
    # a read-only store dir) forbids.
    #
    # Converting an already-linked directory this way is DESTRUCTIVE — recursive
    # writes files through the surviving symlink and into the checkout. The
    # unlinkStaleConfigDirs entry below is what makes it safe. docs/adr/0002.
    "mango" = {
      source = ../../dotfiles/mango;
      recursive = true;
    };

    # --- Editors ------------------------------------------------------------
    # Plain `source`: lua/config/lazy.lua puts lazy-lock.json in stdpath("state"),
    # so nothing writes in here.
    "nvim".source = ../../dotfiles/nvim;

    # --- Shell --------------------------------------------------------------
    # `zsh/conf.d`, not `zsh` — home-manager owns ~/.config/zsh/.zshrc, and two
    # owners on one path is an activation failure.
    "zsh/conf.d".source = ../../dotfiles/zsh/conf.d;

    # --- Store-based ---------------------------------------------------------
    "glow".source = ../../dotfiles/glow; # no home-manager module at this pin

    # Stays here rather than using `services.swaync`, which declares the
    # systemd unit masked in default.nix. autostart.conf owns swaync's
    # lifecycle so a restyle applies on mode switch; adopting the module hands
    # that to systemd. Never run both.
    "swaync".source = ../../dotfiles/swaync;

    # --- Managed as FILES, not directories -----------------------------------
    # Pins the tracked config read-only while leaving the DIRECTORY writable, so
    # sibling runtime files still work. The cost: the config can no longer be
    # changed from inside the app.
    "Kvantum/kvantum.kvconfig".source = ../../dotfiles/Kvantum/kvantum.kvconfig;
    # `#` starts a comment in Nix, so a bare path swallows the semicolon and
    # errors on the NEXT line. Concatenating a string avoids the lexer.
    "Kvantum/Gruvbox#".source = ../../dotfiles/Kvantum + "/Gruvbox#";

    # Nix owns GTK settings (theme.nix), so pinning nwg-look's own state
    # read-only stops the GUI fighting the declared config.
    "nwg-look/config".source = ../../dotfiles/nwg-look/config;

    # settings.ini, gtk.css and bookmarks are generated in theme.nix; only the
    # referenced assets are carried here.
    "gtk-3.0/assets".source = ../../dotfiles/gtk-3.0/assets;
    "gtk-3.0/colors.css".source = ../../dotfiles/gtk-3.0/colors.css;
    "gtk-4.0/colors.css".source = ../../dotfiles/gtk-4.0/colors.css;

    # --- The one genuine holdout ---------------------------------------------
    # corectrl writes corectrl.ini and profiles/*.ccpro from its GUI, and that
    # GUI is the point of the program. Pinning them removes the only way it is
    # used.
    "corectrl".source = link "corectrl";
  };

  # gh, glab-cli, gpu-screen-recorder and opencode are deliberately NOT linked:
  # they hold credentials, so they are gitignored, so a link would rename the
  # real directory aside and leave a dangling one. Restored from backup instead.

  # ~/.zshenv sets ZDOTDIR and is written by home-manager when programs.zsh.dotDir
  # is set, so it is not linked here.

  # Store-based rather than `link`: nothing writes into ~/.scripts, and Nix
  # preserves the executable bit. audio.nix declares a unit whose ExecStart
  # points in here, so it has to be part of the flake. home.sessionPath adds it
  # to PATH.
  home.file.".scripts".source = ../../dotfiles/scripts;

  # Removes a config directory that is still an out-of-store symlink before
  # home-manager links anything into it — otherwise `recursive = true` writes
  # through the old link and clobbers the checkout (docs/adr/0002). A no-op once
  # converted, kept so the conversion reproduces on a fresh machine.
  #
  # DERIVED from xdg.configFile, not hardcoded: an earlier hand-maintained list
  # silently missed the next batch of conversions and clobbered ten tracked
  # files.
  home.activation.unlinkStaleConfigDirs =
    let
      # "gtk-3.0/assets" guards "~/.config/gtk-3.0" — the path a stale symlink
      # would sit at.
      topLevel = lib.unique (
        map (n: lib.head (lib.splitString "/" n)) (lib.attrNames config.xdg.configFile)
      );
    in
    lib.hm.dag.entryBefore [ "checkLinkTargets" ] (
      lib.concatMapStrings (d: ''
        if [ -L "${config.xdg.configHome}/${d}" ]; then
          run rm $VERBOSE_ARG "${config.xdg.configHome}/${d}"
        fi
      '') topLevel
    );

  # Top-level dirs GTK file managers omit from the ~ view (Ctrl+H to show).
  home.file.".hidden".text = ''
    Android
    Applications
    blender
    colors
    go
    log
    R
    share
    temp
    vaults
    winboat
    Zomboid
  '';
}
