#!/usr/bin/env bash
# Shared definitions for the mango scripts. Source it, don't run it:
#
#   . "$HOME/.config/mango/scripts/lib.sh"
#
# This exists because the state directory used to be re-derived in every script
# that touched it, each with its own copy of the `${XDG_STATE_HOME:-…}` fallback
# and its own default value. That is how the mode switch broke one-way on
# 2026-07-31: `desktop-mode.sh` still resolved `current-mode` under the old
# `$MANGO_DIR/state`, found nothing, fell back to "tiling", and so reported
# tiling as active in every mode — which made switching back look like a no-op.
# Nothing was logged. One definition, in one file, forecloses that whole class.

# shellcheck shell=bash
# SC2034: these are consumed by the scripts that source this file, not here.
# shellcheck disable=SC2034
MANGO_DIR="$HOME/.config/mango"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/mango"
# shellcheck disable=SC2034
WAYBAR_DIR="$MANGO_DIR/waybar"
# wayle's config lives under ~/.config/wayle, not in the mango tree: it is
# wayle's own XDG directory and home-manager writes the layouts into it.
# shellcheck disable=SC2034
WAYLE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/wayle"

# Read a state file, or echo the default if it is missing or empty. Every
# reader wants exactly this, and the defaults must agree across scripts.
state() {
	local file="$STATE_DIR/$1" fallback="$2" value
	value=$(cat "$file" 2>/dev/null) || true
	[ -n "$value" ] && printf '%s\n' "$value" || printf '%s\n' "$fallback"
}

state_write() {
	mkdir -p "$STATE_DIR"
	printf '%s\n' "$2" >"$STATE_DIR/$1"
}

# The three switches, with their defaults in one place.
#
# `bar-*`, not `waybar-*`: the tiling bar is wayle now (docs/adr/0045) and the
# state outlives whichever program draws it. The rename cost one reset to the
# defaults below, which is why it happened in the same change as the swap
# rather than later — a half-renamed state file is the one-way mode switch
# this file's header describes.
current_mode() { state current-mode tiling; } # tiling | noctalia
bar_layout() { state bar-layout full; }       # full | focus | minimal
bar_position() { state bar-position top; }    # top | bottom

# Run `rofi -dmenu` sized to its own input. Entries on stdin, the choice on
# stdout, `$1` the ceiling, everything after it passed through to rofi.
#
# `-theme-str`, not `-l`. On rofi 2.0 the theme overrides the command line, so
# the `-l` menus passed here was accepted and ignored: every menu rendered
# `lines: 12` tall whatever it held — a two-entry picker with ten blank rows
# below it, and the control centre paging silently the moment it grew past
# twelve. `dynamic: true` does not fix that; it governs resize while filtering,
# not fit-to-contents. docs/gotchas.md -> rofi.
#
# The ceiling is per menu and always explicit. A fixed picker wants no cap worth
# hitting; a list that comes from the machine — access points, paired devices,
# the clipboard — must not grow to the height of the screen.
rofi_menu() {
	local max=$1 entries n
	shift
	entries=$(cat)
	# `grep -c ''` counts a final line with no newline, which `wc -l` does not.
	n=$(printf '%s\n' "$entries" | grep -c '')
	if [ "$n" -gt "$max" ]; then n=$max; fi
	# Not zero: rofi draws the prompt and nothing else, which reads as a menu
	# that failed to load rather than one with nothing to offer.
	if [ "$n" -lt 1 ]; then n=1; fi
	# `-i` as well as `case-sensitive: false` in config.rasi: the file is what
	# actually decides on rofi 2.0, and this is the half a reader of a menu
	# script can see.
	printf '%s\n' "$entries" | rofi -dmenu -i -theme-str "listview { lines: $n; }" "$@"
}

# noctalia mode runs its own bar, so the three wayle scripts must refuse rather
# than start one over it. Here, not in each of them, for the reason the header
# gives: a reader and a writer that disagree fail silently.
mode_has_bar() { [ "$(current_mode)" != noctalia ]; }

# Point a mode's colours at kitty, foot, rofi, ncspot and Equibop —
# docs/adr/0034. Targets are generated by modules/home/mode-theme.nix.
#
# Takes the mode, not a scheme name: a scheme name crossing this boundary is a
# value Nix and this file must spell alike, the drift lib.sh exists to stop.
#
# Verify before linking, then link as a set — a dangling link is silent in
# kitty, rofi and ncspot and fatal in foot, so a half-applied theme must not be
# reachable. Equibop needs no link (it takes a filename) but fails the same
# silent way, so it is verified with the rest.
apply_theme() {
	local mode="$1" cfg="${XDG_CONFIG_HOME:-$HOME/.config}" missing=""

	# <link>|<target>, both relative to $cfg. The link points at the ~/.config
	# path and not into the store, so it survives a rebuild: the target is
	# itself a home-manager symlink and gets re-pointed there.
	local pairs=(
		"kitty/current-theme.conf|kitty/colors-$mode.conf"
		"foot/themes/noctalia|foot/colors-$mode"
		"rofi/colors.rasi|rofi/colors-$mode.rasi"
		"ncspot/config.toml|ncspot/colors-$mode.toml"
	)

	# Not a link — a name, written into Equibop's own settings below.
	local eq_theme="equibop/themes/$mode.theme.css"

	local pair link target
	for pair in "${pairs[@]}"; do
		target="${pair#*|}"
		[ -s "$cfg/$target" ] || missing="$missing $target"
	done
	[ -s "$cfg/$eq_theme" ] || missing="$missing $eq_theme"
	if [ -n "$missing" ]; then
		notify-send -u critical "Theme" "Colours for '$mode' not applied — missing:$missing"
		return 1
	fi

	for pair in "${pairs[@]}"; do
		link="${pair%%|*}"
		target="${pair#*|}"
		ln -sfn "$cfg/$target" "$cfg/$link"
	done

	# kitty re-reads its config, includes and all, on SIGUSR1. Match `comm` with
	# `^\.?kitty$` and not `-x kitty`: nixpkgs wraps some binaries, so comm can
	# be `.kitty-wrapped`, and `-f` would match this script's own command line.
	pkill -USR1 '^\.?kitty$' 2>/dev/null || true

	# Neither foot nor ncspot can be told: foot 1.27 has no config re-read, and
	# ncspot reads config.toml once at startup. Said every time rather than
	# written down once, and only for what is actually running.
	#
	# `if`, not `pgrep ... && stale=`: a bare `a && b` whose `a` fails fails the
	# statement, which would exit under any caller that later adds `set -e`.
	local stale=""
	if pgrep '^\.?foot' >/dev/null 2>&1; then stale="foot"; fi
	if pgrep '^\.?ncspot' >/dev/null 2>&1; then stale="${stale:+$stale and }ncspot"; fi
	if [ -n "$stale" ]; then
		notify-send "Theme" "Colours now '$mode'. $stale cannot reload — restart to pick them up."
	fi

	# Equibop, by name — it ignores a name matching no file without logging,
	# hence the check above. No settings.json until it has been launched once.
	local eq="$HOME/.config/equibop/settings/settings.json"
	if [ -f "$eq" ]; then
		jq --arg t "$mode.theme.css" '.enabledThemes = [$t]' "$eq" >"$eq.tmp" && mv "$eq.tmp" "$eq"
	fi
}

# Apply a desktop mode. modes/tiling.sh and the since-removed modes/hud.sh
# (docs/adr/0035) differed only in two
# names and were otherwise a byte-identical copy of the body below, including
# the equibop block — so a fix to one silently missed the other.
apply_mode() {
	local mode="$1"

	# Checked before anything is written. `ln -sfn` to a missing target succeeds
	# where the copy this replaced failed loudly, and a dangling config.conf
	# drops mango to built-in defaults with no keybinds. Before state_write
	# specifically, so a mode that was not applied is not recorded as active —
	# see this file's header. docs/adr/0040.
	if [ ! -s "$MANGO_DIR/$mode/$mode.conf" ]; then
		notify-send -u critical "Desktop mode" "'$mode' not applied — $mode/$mode.conf is missing"
		return 1
	fi

	state_write current-mode "$mode"

	# One inhibitor owner per mode. noctalia holds keep-awake over quickshell's
	# own IdleInhibitor and its IPC offers toggle/enable/disable/enableFor and
	# No getter (checked against 4.7.7), so there is no way to read its state
	# back and keep the two in step. Whichever is not the current mode's would
	# sit there holding the machine awake with its indicator reading off.
	#
	# Handing it over means a mode switch releases the inhibitor, which is the
	# exact failure docs/adr/0031 was written to remove — so this is the one
	# place it happens deliberately, and it says so. The guard is what makes the
	# message honest: no notification when there was nothing to release.
	#
	# One-way. Leaving noctalia does not re-arm wlinhibit, because there is no
	# getter to ask whether noctalia was holding one.
	if [ "$mode" = noctalia ] && "$MANGO_DIR/scripts/system/idle-inhibit.sh" is-on; then
		"$MANGO_DIR/scripts/system/idle-inhibit.sh" off
		notify-send "Keep awake" "Released entering noctalia — SUPER+SHIFT+A holds it again here"
	fi

	# A link, not a copy — the only runtime write left in ~/.config/mango. mango
	# is launched with no `-c`, so cli_config_path stays empty and every `./` in
	# the tree still resolves against ~/.config/mango/. Target checked at the
	# top. docs/adr/0040.
	ln -sfn "$MANGO_DIR/$mode/$mode.conf" "$MANGO_DIR/config.conf"

	# The colours kitty, foot, rofi, ncspot and Equibop read. After config.conf
	# is in place, so that a failure here leaves a mode that is otherwise fully
	# applied rather than one that stopped halfway.
	apply_theme "$mode"
}
