#!/usr/bin/env bash
# Shared definitions for the mango scripts. Source it, don't run it:
#
#   . "$HOME/.config/mango/scripts/lib.sh"
#
# This exists because the state directory used to be re-derived in every script
# that touched it, each with its own copy of the `${XDG_STATE_HOME:-…}` fallback
# and its own default value. That is how the mode switch broke one-way on
# 2026-07-31: `desktop-mode.sh` still resolved `current-mode` under the old
# `$MANGO_DIR/state`, found nothing, fell back to "tiling", and so reported
# tiling as active in every mode — which made switching back look like a no-op.
# Nothing was logged. One definition, in one file, forecloses that whole class.

# shellcheck shell=bash
# SC2034: these are consumed by the scripts that source this file, not here.
# shellcheck disable=SC2034
MANGO_DIR="$HOME/.config/mango"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/mango"
# shellcheck disable=SC2034
WAYBAR_DIR="$MANGO_DIR/waybar"

# Read a state file, or echo the default if it is missing or empty. Every
# reader wants exactly this, and the defaults must agree across scripts.
state() {
    local file="$STATE_DIR/$1" fallback="$2" value
    value=$(cat "$file" 2>/dev/null) || true
    [ -n "$value" ] && printf '%s\n' "$value" || printf '%s\n' "$fallback"
}

state_write() {
    mkdir -p "$STATE_DIR"
    printf '%s\n' "$2" > "$STATE_DIR/$1"
}

# The three switches, with their defaults in ONE place.
current_mode() { state current-mode tiling; }      # tiling | noctalia
waybar_layout() { state waybar-layout full; }      # full | focus | minimal
waybar_position() { state waybar-position top; }   # top | bottom

# noctalia mode runs its own bar, so the three waybar scripts must refuse
# rather than start one over it. Here, not in each of them, for the reason the
# header gives: a reader and a writer that disagree fail silently.
mode_has_waybar() { [ "$(current_mode)" != noctalia ]; }

# Point kitty, foot and rofi at a mode's generated colours — docs/adr/0034.
#
# All three run in EVERY mode and read one fixed path, so each reads through an
# indirection this re-points. The targets are generated by
# modules/home/mode-theme.nix, which is where the odd link names are explained.
#
# TAKES THE MODE, NOT A SCHEME NAME. The generated files are keyed by mode for
# that reason: a scheme name crossing this boundary would be a value Nix and
# this file both have to spell the same way, which is the drift this whole file
# was extracted to stop.
#
# VERIFY BEFORE LINKING, all of them, then link. A dangling symlink fails
# UNLOGGED in every consumer here — rofi's `@import`, kitty's `include` and
# foot's `include` all skip what they cannot resolve, and ncspot treats a
# missing config.toml as a valid empty one. Every case renders in the app's own
# defaults, which looks like a theme that did not apply rather than a file that
# is not there. Refusing as a set also means a half-applied theme is not
# reachable: either the mode's colours are all there or none of them move.
#
# Equibop is the odd one and needs no link: it enables a theme by FILENAME out
# of its own settings.json, which this rewrites — an indirection it already
# had. It gets verified with the rest because it fails the same way, silently.
apply_theme() {
    local mode="$1" cfg="${XDG_CONFIG_HOME:-$HOME/.config}" missing=""

    # <link>|<target>, both relative to $cfg. The link points at the ~/.config
    # path and not into the store, so it survives a rebuild: the TARGET is
    # itself a home-manager symlink and gets re-pointed there.
    local pairs=(
        "kitty/current-theme.conf|kitty/colors-$mode.conf"
        "foot/themes/noctalia|foot/colors-$mode"
        "rofi/colors.rasi|rofi/colors-$mode.rasi"
        "ncspot/config.toml|ncspot/colors-$mode.toml"
    )

    # Not a link — a name, written into Equibop's own settings below.
    local eq_theme="equibop/themes/$mode.theme.css"

    local pair link target
    for pair in "${pairs[@]}"; do
        target="${pair#*|}"
        [ -s "$cfg/$target" ] || missing="$missing $target"
    done
    [ -s "$cfg/$eq_theme" ] || missing="$missing $eq_theme"
    if [ -n "$missing" ]; then
        notify-send -u critical "Theme" "Colours for '$mode' not applied — missing:$missing"
        return 1
    fi

    for pair in "${pairs[@]}"; do
        link="${pair%%|*}"
        target="${pair#*|}"
        ln -sfn "$cfg/$target" "$cfg/$link"
    done

    # kitty re-reads its config, includes and all, on SIGUSR1. Match `comm` with
    # `^\.?kitty$` and not `-x kitty`: nixpkgs wraps some binaries, so comm can
    # be `.kitty-wrapped`, and `-f` would match this script's own command line.
    pkill -USR1 '^\.?kitty$' 2>/dev/null || true

    # foot CANNOT be told. 1.27's SIGUSR1/2 switch between the sections already
    # loaded; there is no config re-read at all, so open windows keep the old
    # palette until they are closed. ncspot is worse: it reads config.toml once
    # at startup, so a running one keeps its colours until it is restarted.
    # Undocumented, either reads as the swap being broken — so it is said, every
    # time, rather than written down once. Named only when actually running, so
    # the message stays true instead of listing caveats nobody has open.
    #
    # `if`, not `pgrep ... && stale=`: a bare `a && b` whose `a` fails makes the
    # whole statement fail, so the one-liner form would be an exit under any
    # caller that later adds `set -e`. None does today; none has to remember.
    local stale=""
    if pgrep '^\.?foot' >/dev/null 2>&1; then stale="foot"; fi
    if pgrep '^\.?ncspot' >/dev/null 2>&1; then stale="${stale:+$stale and }ncspot"; fi
    if [ -n "$stale" ]; then
        notify-send "Theme" "Colours now '$mode'. $stale cannot reload — restart to pick them up."
    fi

    # Equibop, by name. It ignores a name matching no file WITHOUT logging,
    # which is why the file was verified above. No settings.json until Equibop
    # has been launched once, which is the normal state on a fresh machine —
    # skip rather than erroring on every mode switch.
    local eq="$HOME/.config/equibop/settings/settings.json"
    if [ -f "$eq" ]; then
        jq --arg t "$mode.theme.css" '.enabledThemes = [$t]' "$eq" > "$eq.tmp" && mv "$eq.tmp" "$eq"
    fi
}

# Apply a desktop mode. modes/tiling.sh and the since-removed modes/hud.sh
# (docs/adr/0035) differed only in two
# names and were otherwise a byte-identical copy of the body below, including
# the equibop block — so a fix to one silently missed the other.
apply_mode() {
    local mode="$1"
    state_write current-mode "$mode"

    # ONE INHIBITOR OWNER PER MODE. noctalia holds keep-awake over quickshell's
    # own IdleInhibitor and its IPC offers toggle/enable/disable/enableFor and
    # NO getter (checked against 4.7.7), so there is no way to read its state
    # back and keep the two in step. Whichever is not the current mode's would
    # sit there holding the machine awake with its indicator reading off.
    #
    # Handing it over means a mode switch releases the inhibitor, which is the
    # exact failure docs/adr/0031 was written to remove — so this is the one
    # place it happens deliberately, and it SAYS SO. The guard is what makes the
    # message honest: no notification when there was nothing to release.
    #
    # One-way. Leaving noctalia does not re-arm wlinhibit, because there is no
    # getter to ask whether noctalia was holding one.
    if [ "$mode" = noctalia ] && "$MANGO_DIR/scripts/system/idle-inhibit.sh" is-on; then
        "$MANGO_DIR/scripts/system/idle-inhibit.sh" off
        notify-send "Keep awake" "Released entering noctalia — SUPER+SHIFT+A holds it again here"
    fi

    # `install -m 644`, NOT `cp`. ~/.config/mango is a store path, so
    # <mode>.conf is a read-only 0444 file and `cp` gives a new destination the
    # source's mode — the first switch wrote a 0444 config.conf and every
    # switch after it died with `Permission denied`. `install -m` sets the mode
    # explicitly rather than inheriting it.
    install -m 644 "$MANGO_DIR/$mode/$mode.conf" "$MANGO_DIR/config.conf"

    # The colours kitty, foot, rofi, ncspot and Equibop read. AFTER config.conf
    # is in place, so that a failure here leaves a mode that is otherwise fully
    # applied rather than one that stopped halfway.
    apply_theme "$mode"
}
