[main]
#include=~/.config/foot/themes/noctalia
include=~/.config/foot/active-theme.ini

shell=zsh
title=foot
#font=SFMono Nerd Font Mono SemiBold:size=12
#font=JetBrains Mono Nerd Font:size=12
font=Hack Nerd Font Mono:size=11
#font=Monaspace Neon NF:size=12:weight=120

letter-spacing=0
dpi-aware=no
pad=20x15
bold-text-in-bright=no
gamma-correct-blending=no


[scrollback]
lines=10000

[cursor]
style=beam
beam-thickness=1.5
[colors]
#alpha=0.78

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
search-start=Control+Shift+f

[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3 Control+G
